spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_springboot?useSSL=false
    username: root
    password: chen892066
    driver-class-name: com.mysql.jdbc.Driver
    type: org.springframework.jdbc.datasource.DriverManagerDataSource

  servlet:
    multipart:
      location: e:/fileupload
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.example.demo.pojo
server:
  port: 8082
